### ISSUE TITLE
genome names cannot contain dashes?

### ISSUE THREAD

**Issue by taylorreiter** [elizabethmcd/metabolisHMM#49]
Hello! I ran metabolishmm and received the following error:
```
$  summarize-metabolism --inp
ut in_genomes --output out_genomes --metadata metabolishmm_metadata.csv --aggregate OFF
```
```
metabolisHMM v2.21
Reformatting fasta files...
Screening curated metabolic markers...
Parsing all results...
/home/tereiter/miniconda3/envs/metabolishmm/bin/summarize-metabolism:162: DeprecationWarning: '
U' mode is deprecated
  with open(result, "rU") as input:
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/envs/metabolishmm/bin/summarize-metabolism", line 162, in <mo
dule>
    with open(result, "rU") as input:
FileNotFoundError: [Errno 2] No such file or directory: 'out_genomes/out/QinJ_2012__CON/QinJ_20
12__CON-091__bin.20-ccoP_TIGR00782.out'

out_genomes/out/QinJ_2012__CON/QinJ_2012__CON-091__bin.20-ccoP_TIGR00782.out
```

When I removed the dashes from the genome name, metabolishmm ran fine.

**Comment by elizabethmcd** [comment]
Hi Taylor. Yes, I have it required that genome names can only have underscores in them and not hyphens due to how it handles intermediary files. I originally just had this in the wiki documentation at the beginning of explaining workflows: https://github.com/elizabethmcd/metabolisHMM/wiki/Workflows#single-marker-phylogeny, but I should add an exception that checks for this and alerts the user.

**Comment by taylorreiter** [comment]
Thank you, I missed that in the documentation, sorry! :)
