### ISSUE TITLE
Error running summarize-metabolism

### ISSUE THREAD

**Issue by bbaker567** [elizabethmcd/metabolisHMM#57]
Hello,
I am running the workflow summarize-metabolism and I keep running into an error but without much detail.

FileNotFoundError: [Errno 2] No such file or directory: '/home/brittany/Dropbox/PhD_2020/other_mags/metabolisHMM/dallol_subset_Jan25/out/DAL/DAL-WCL_45_84C1R-fdhA_TIGR01591.out'

I am not quite sure how to fix this. Or what the work around is. Any suggestions are appreciated! 

Thank you!

More details of the std output :
#############################################
metabolisHMM v2.21
Reformatting fasta files...
Screening curated metabolic markers...
Parsing all results...
/home/brittany/.local/bin/summarize-metabolism:162: DeprecationWarning: 'U' mode is deprecated
  with open(result, "rU") as input:
Traceback (most recent call last):
  File "/home/brittany/.local/bin/summarize-metabolism", line 162, in <module>
    with open(result, "rU") as input:
FileNotFoundError: [Errno 2] No such file or directory: '/home/brittany/Dropbox/PhD_2020/other_mags/metabolisHMM/dallol_subset_Jan25/out/DAL/DAL-WCL_45_84C1R-fdhA_TIGR01591.out'

**Comment by elizabethmcd** [comment]
In the `out` subdirectory in your results folder, is there anything there? If not it suggests something is wrong with running the HMM-search step for each marker. Alternatively, I think because you have dashes/hyphens in your genome names that needs to be changed, which you can do with: `rename 's/-/_/g' *` because these files need to be formatted where it spilts on `-` to compare each genome-marker pair. This is explained in the [wiki](https://github.com/elizabethmcd/metabolisHMM/wiki/Workflows) but I should add a function to check if filenames have dashes in them and warn the user.

Hope that helps!

**Comment by bbaker567** [comment]
rename 's/-/_/g' * fixed it! Thank you, I should have read the wiki more carefully :)
